INSERT INTO `countries` VALUES (NULL,'AF', 'Afghanistan','أفغانستان','Afghan','أفغانستاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AL', 'Albania','ألبانيا','Albanian','ألباني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AX', 'Aland Islands','جزر آلاند','Aland Islander','آلاندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'DZ', 'Algeria','الجزائر','Algerian','جزائري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AS', 'American Samoa','ساموا-الأمريكي','American Samoan','أمريكي سامواني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AD', 'Andorra','أندورا','Andorran','أندوري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AO', 'Angola','أنغولا','Angolan','أنقولي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AI', 'Anguilla','أنغويلا','Anguillan','أنغويلي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AQ', 'Antarctica','أنتاركتيكا','Antarctican','أنتاركتيكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AG', 'Antigua and Barbuda','أنتيغوا وبربودا','Antiguan','بربودي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AR', 'Argentina','الأرجنتين','Argentinian','أرجنتيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AM', 'Armenia','أرمينيا','Armenian','أرميني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AW', 'Aruba','أروبه','Aruban','أوروبهيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AU', 'Australia','أستراليا','Australian','أسترالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AT', 'Austria','النمسا','Austrian','نمساوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AZ', 'Azerbaijan','أذربيجان','Azerbaijani','أذربيجاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BS', 'Bahamas','الباهاماس','Bahamian','باهاميسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BH', 'Bahrain','البحرين','Bahraini','بحريني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BD', 'Bangladesh','بنغلاديش','Bangladeshi','بنغلاديشي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BB', 'Barbados','بربادوس','Barbadian','بربادوسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BY', 'Belarus','روسيا البيضاء','Belarusian','روسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BE', 'Belgium','بلجيكا','Belgian','بلجيكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BZ', 'Belize','بيليز','Belizean','بيليزي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BJ', 'Benin','بنين','Beninese','بنيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BL', 'Saint Barthelemy','سان بارتيلمي','Saint Barthelmian','سان بارتيلمي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BM', 'Bermuda','جزر برمودا','Bermudan','برمودي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BT', 'Bhutan','بوتان','Bhutanese','بوتاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BO', 'Bolivia','بوليفيا','Bolivian','بوليفي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BA', 'Bosnia and Herzegovina','البوسنة و الهرسك','Bosnian / Herzegovinian','بوسني/هرسكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BW', 'Botswana','بوتسوانا','Botswanan','بوتسواني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BV', 'Bouvet Island','جزيرة بوفيه','Bouvetian','بوفيهي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BR', 'Brazil','البرازيل','Brazilian','برازيلي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'IO', 'British Indian Ocean Territory','إقليم المحيط الهندي البريطاني','British Indian Ocean Territory','إقليم المحيط الهندي البريطاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BN', 'Brunei Darussalam','بروني','Bruneian','بروني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BG', 'Bulgaria','بلغاريا','Bulgarian','بلغاري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BF', 'Burkina Faso','بوركينا فاسو','Burkinabe','بوركيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'BI', 'Burundi','بوروندي','Burundian','بورونيدي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KH', 'Cambodia','كمبوديا','Cambodian','كمبودي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CM', 'Cameroon','كاميرون','Cameroonian','كاميروني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CA', 'Canada','كندا','Canadian','كندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CV', 'Cape Verde','الرأس الأخضر','Cape Verdean','الرأس الأخضر',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KY', 'Cayman Islands','جزر كايمان','Caymanian','كايماني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CF', 'Central African Republic','جمهورية أفريقيا الوسطى','Central African','أفريقي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TD', 'Chad','تشاد','Chadian','تشادي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CL', 'Chile','شيلي','Chilean','شيلي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CN', 'China','الصين','Chinese','صيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CX', 'Christmas Island','جزيرة عيد الميلاد','Christmas Islander','جزيرة عيد الميلاد',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CC', 'Cocos (Keeling) Islands','جزر كوكوس','Cocos Islander','جزر كوكوس',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CO', 'Colombia','كولومبيا','Colombian','كولومبي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KM', 'Comoros','جزر القمر','Comorian','جزر القمر',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CG', 'Congo','الكونغو','Congolese','كونغي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CK', 'Cook Islands','جزر كوك','Cook Islander','جزر كوك',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CR', 'Costa Rica','كوستاريكا','Costa Rican','كوستاريكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'HR', 'Croatia','كرواتيا','Croatian','كوراتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CU', 'Cuba','كوبا','Cuban','كوبي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CY', 'Cyprus','قبرص','Cypriot','قبرصي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CW', 'Curaçao','كوراساو','Curacian','كوراساوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CZ', 'Czech Republic','الجمهورية التشيكية','Czech','تشيكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'DK', 'Denmark','الدانمارك','Danish','دنماركي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'DJ', 'Djibouti','جيبوتي','Djiboutian','جيبوتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'DM', 'Dominica','دومينيكا','Dominican','دومينيكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'DO', 'Dominican Republic','الجمهورية الدومينيكية','Dominican','دومينيكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'EC', 'Ecuador','إكوادور','Ecuadorian','إكوادوري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'EG', 'Egypt','مصر','Egyptian','مصري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SV', 'El Salvador','إلسلفادور','Salvadoran','سلفادوري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GQ', 'Equatorial Guinea','غينيا الاستوائي','Equatorial Guinean','غيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ER', 'Eritrea','إريتريا','Eritrean','إريتيري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'EE', 'Estonia','استونيا','Estonian','استوني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ET', 'Ethiopia','أثيوبيا','Ethiopian','أثيوبي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'FK', 'Falkland Islands (Malvinas)','جزر فوكلاند','Falkland Islander','فوكلاندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'FO', 'Faroe Islands','جزر فارو','Faroese','جزر فارو',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'FJ', 'Fiji','فيجي','Fijian','فيجي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'FI', 'Finland','فنلندا','Finnish','فنلندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'FR', 'France','فرنسا','French','فرنسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GF', 'French Guiana','غويانا الفرنسية','French Guianese','غويانا الفرنسية',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PF', 'French Polynesia','بولينيزيا الفرنسية','French Polynesian','بولينيزيي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TF', 'French Southern and Antarctic Lands','أراض فرنسية جنوبية وأنتارتيكية','French','أراض فرنسية جنوبية وأنتارتيكية',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GA', 'Gabon','الغابون','Gabonese','غابوني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GM', 'Gambia','غامبيا','Gambian','غامبي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GE', 'Georgia','جيورجيا','Georgian','جيورجي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'DE', 'Germany','ألمانيا','German','ألماني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GH', 'Ghana','غانا','Ghanaian','غاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GI', 'Gibraltar','جبل طارق','Gibraltar','جبل طارق',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GG', 'Guernsey','غيرنزي','Guernsian','غيرنزي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GR', 'Greece','اليونان','Greek','يوناني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GL', 'Greenland','جرينلاند','Greenlandic','جرينلاندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GD', 'Grenada','غرينادا','Grenadian','غرينادي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GP', 'Guadeloupe','جزر جوادلوب','Guadeloupe','جزر جوادلوب',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GU', 'Guam','جوام','Guamanian','جوامي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GT', 'Guatemala','غواتيمال','Guatemalan','غواتيمالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GN', 'Guinea','غينيا','Guinean','غيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GW', 'Guinea-Bissau','غينيا-بيساو','Guinea-Bissauan','غيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GY', 'Guyana','غيانا','Guyanese','غياني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'HT', 'Haiti','هايتي','Haitian','هايتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'HM', 'Heard and Mc Donald Islands','جزيرة هيرد وجزر ماكدونالد','Heard and Mc Donald Islanders','جزيرة هيرد وجزر ماكدونالد',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'HN', 'Honduras','هندوراس','Honduran','هندوراسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'HK', 'Hong Kong','هونغ كونغ','Hongkongese','هونغ كونغي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'HU', 'Hungary','المجر','Hungarian','مجري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'IS', 'Iceland','آيسلندا','Icelandic','آيسلندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'IN', 'India','الهند','Indian','هندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'IM', 'Isle of Man','جزيرة مان','Manx','ماني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ID', 'Indonesia','أندونيسيا','Indonesian','أندونيسيي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'IR', 'Iran','إيران','Iranian','إيراني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'IQ', 'Iraq','العراق','Iraqi','عراقي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'IE', 'Ireland','إيرلندا','Irish','إيرلندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'IL', 'Israel','إسرائيل','Israeli','إسرائيلي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'IT', 'Italy','إيطاليا','Italian','إيطالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CI', 'Ivory Coast','ساحل العاج','Ivory Coastian','ساحل العاج',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'JE', 'Jersey','جيرزي','Jersian','جيرزي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'JM', 'Jamaica','جمايكا','Jamaican','جمايكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'JP', 'Japan','اليابان','Japanese','ياباني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'JO', 'Jordan','الأردن','Jordanian','أردني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KZ', 'Kazakhstan','كازاخستان','Kazakh','كازاخستاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KE', 'Kenya','كينيا','Kenyan','كيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KI', 'Kiribati','كيريباتي','I-Kiribati','كيريباتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KP', 'Korea(North Korea)','كوريا الشمالية','North Korean','كوري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KR', 'Korea(South Korea)','كوريا الجنوبية','South Korean','كوري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'XK', 'Kosovo','كوسوفو','Kosovar','كوسيفي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KW', 'Kuwait','الكويت','Kuwaiti','كويتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KG', 'Kyrgyzstan','قيرغيزستان','Kyrgyzstani','قيرغيزستاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LA', 'Lao PDR','لاوس','Laotian','لاوسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LV', 'Latvia','لاتفيا','Latvian','لاتيفي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LB', 'Lebanon','لبنان','Lebanese','لبناني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LS', 'Lesotho','ليسوتو','Basotho','ليوسيتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LR', 'Liberia','ليبيريا','Liberian','ليبيري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LY', 'Libya','ليبيا','Libyan','ليبي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LI', 'Liechtenstein','ليختنشتين','Liechtenstein','ليختنشتيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LT', 'Lithuania','لتوانيا','Lithuanian','لتوانيي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LU', 'Luxembourg','لوكسمبورغ','Luxembourger','لوكسمبورغي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LK', 'Sri Lanka','سريلانكا','Sri Lankian','سريلانكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MO', 'Macau','ماكاو','Macanese','ماكاوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MK', 'Macedonia','مقدونيا','Macedonian','مقدوني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MG', 'Madagascar','مدغشقر','Malagasy','مدغشقري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MW', 'Malawi','مالاوي','Malawian','مالاوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MY', 'Malaysia','ماليزيا','Malaysian','ماليزي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MV', 'Maldives','المالديف','Maldivian','مالديفي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ML', 'Mali','مالي','Malian','مالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MT', 'Malta','مالطا','Maltese','مالطي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MH', 'Marshall Islands','جزر مارشال','Marshallese','مارشالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MQ', 'Martinique','مارتينيك','Martiniquais','مارتينيكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MR', 'Mauritania','موريتانيا','Mauritanian','موريتانيي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MU', 'Mauritius','موريشيوس','Mauritian','موريشيوسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'YT', 'Mayotte','مايوت','Mahoran','مايوتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MX', 'Mexico','المكسيك','Mexican','مكسيكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'FM', 'Micronesia','مايكرونيزيا','Micronesian','مايكرونيزيي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MD', 'Moldova','مولدافيا','Moldovan','مولديفي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MC', 'Monaco','موناكو','Monacan','مونيكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MN', 'Mongolia','منغوليا','Mongolian','منغولي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ME', 'Montenegro','الجبل الأسود','Montenegrin','الجبل الأسود',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MS', 'Montserrat','مونتسيرات','Montserratian','مونتسيراتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MA', 'Morocco','المغرب','Moroccan','مغربي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MZ', 'Mozambique','موزمبيق','Mozambican','موزمبيقي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MM', 'Myanmar','ميانمار','Myanmarian','ميانماري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NA', 'Namibia','ناميبيا','Namibian','ناميبي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NR', 'Nauru','نورو','Nauruan','نوري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NP', 'Nepal','نيبال','Nepalese','نيبالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NL', 'Netherlands','هولندا','Dutch','هولندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AN', 'Netherlands Antilles','جزر الأنتيل الهولندي','Dutch Antilier','هولندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NC', 'New Caledonia','كاليدونيا الجديدة','New Caledonian','كاليدوني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NZ', 'New Zealand','نيوزيلندا','New Zealander','نيوزيلندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NI', 'Nicaragua','نيكاراجوا','Nicaraguan','نيكاراجوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NE', 'Niger','النيجر','Nigerien','نيجيري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NG', 'Nigeria','نيجيريا','Nigerian','نيجيري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NU', 'Niue','ني','Niuean','ني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NF', 'Norfolk Island','جزيرة نورفولك','Norfolk Islander','نورفوليكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MP', 'Northern Mariana Islands','جزر ماريانا الشمالية','Northern Marianan','ماريني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'NO', 'Norway','النرويج','Norwegian','نرويجي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'OM', 'Oman','عمان','Omani','عماني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PK', 'Pakistan','باكستان','Pakistani','باكستاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PW', 'Palau','بالاو','Palauan','بالاوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PS', 'Palestine','فلسطين','Palestinian','فلسطيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PA', 'Panama','بنما','Panamanian','بنمي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PG', 'Papua New Guinea','بابوا غينيا الجديدة','Papua New Guinean','بابوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PY', 'Paraguay','باراغواي','Paraguayan','بارغاوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PE', 'Peru','بيرو','Peruvian','بيري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PH', 'Philippines','الفليبين','Filipino','فلبيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PN', 'Pitcairn','بيتكيرن','Pitcairn Islander','بيتكيرني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PL', 'Poland','بولونيا','Polish','بوليني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PT', 'Portugal','البرتغال','Portuguese','برتغالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'PR', 'Puerto Rico','بورتو ريكو','Puerto Rican','بورتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'QA', 'Qatar','قطر','Qatari','قطري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'RE', 'Reunion Island','ريونيون','Reunionese','ريونيوني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'RO', 'Romania','رومانيا','Romanian','روماني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'RU', 'Russian','روسيا','Russian','روسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'RW', 'Rwanda','رواندا','Rwandan','رواندا',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'KN', 'Saint Kitts and Nevis','سانت كيتس ونيفس,','Kittitian/Nevisian','سانت كيتس ونيفس',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'MF', 'Saint Martin (French part)','ساينت مارتن فرنسي','St. Martian(French)','ساينت مارتني فرنسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SX', 'Sint Maarten (Dutch part)','ساينت مارتن هولندي','St. Martian(Dutch)','ساينت مارتني هولندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'LC', 'Saint Pierre and Miquelon','سان بيير وميكلون','St. Pierre and Miquelon','سان بيير وميكلوني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'VC', 'Saint Vincent and the Grenadines','سانت فنسنت وجزر غرينادين','Saint Vincent and the Grenadines','سانت فنسنت وجزر غرينادين',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'WS', 'Samoa','ساموا','Samoan','ساموي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SM', 'San Marino','سان مارينو','Sammarinese','ماريني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ST', 'Sao Tome and Principe','ساو تومي وبرينسيبي','Sao Tomean','ساو تومي وبرينسيبي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SA', 'Saudi Arabia','المملكة العربية السعودية','Saudi Arabian','سعودي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SN', 'Senegal','السنغال','Senegalese','سنغالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'RS', 'Serbia','صربيا','Serbian','صربي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SC', 'Seychelles','سيشيل','Seychellois','سيشيلي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SL', 'Sierra Leone','سيراليون','Sierra Leonean','سيراليوني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SG', 'Singapore','سنغافورة','Singaporean','سنغافوري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SK', 'Slovakia','سلوفاكيا','Slovak','سولفاكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SI', 'Slovenia','سلوفينيا','Slovenian','سولفيني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SB', 'Solomon Islands','جزر سليمان','Solomon Island','جزر سليمان',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SO', 'Somalia','الصومال','Somali','صومالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ZA', 'South Africa','جنوب أفريقيا','South African','أفريقي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GS', 'South Georgia and the South Sandwich','المنطقة القطبية الجنوبية','South Georgia and the South Sandwich','لمنطقة القطبية الجنوبية',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SS', 'South Sudan','السودان الجنوبي','South Sudanese','سوادني جنوبي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ES', 'Spain','إسبانيا','Spanish','إسباني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SH', 'Saint Helena','سانت هيلانة','St. Helenian','هيلاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SD', 'Sudan','السودان','Sudanese','سوداني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SR', 'Suriname','سورينام','Surinamese','سورينامي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SJ', 'Svalbard and Jan Mayen','سفالبارد ويان ماين','Svalbardian/Jan Mayenian','سفالبارد ويان ماين',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SZ', 'Swaziland','سوازيلند','Swazi','سوازيلندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SE', 'Sweden','السويد','Swedish','سويدي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'CH', 'Switzerland','سويسرا','Swiss','سويسري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'SY', 'Syria','سوريا','Syrian','سوري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TW', 'Taiwan','تايوان','Taiwanese','تايواني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TJ', 'Tajikistan','طاجيكستان','Tajikistani','طاجيكستاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TZ', 'Tanzania','تنزانيا','Tanzanian','تنزانيي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TH', 'Thailand','تايلندا','Thai','تايلندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TL', 'Timor-Leste','تيمور الشرقية','Timor-Lestian','تيموري',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TG', 'Togo','توغو','Togolese','توغي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TK', 'Tokelau','توكيلاو','Tokelaian','توكيلاوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TO', 'Tonga','تونغا','Tongan','تونغي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TT', 'Trinidad and Tobago','ترينيداد وتوباغو','Trinidadian/Tobagonian','ترينيداد وتوباغو',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TN', 'Tunisia','تونس','Tunisian','تونسي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TR', 'Turkey','تركيا','Turkish','تركي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TM', 'Turkmenistan','تركمانستان','Turkmen','تركمانستاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TC', 'Turks and Caicos Islands','جزر توركس وكايكوس','Turks and Caicos Islands','جزر توركس وكايكوس',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'TV', 'Tuvalu','توفالو','Tuvaluan','توفالي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'UG', 'Uganda','أوغندا','Ugandan','أوغندي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'UA', 'Ukraine','أوكرانيا','Ukrainian','أوكراني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'AE', 'United Arab Emirates','الإمارات العربية المتحدة','Emirati','إماراتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'GB', 'United Kingdom','المملكة المتحدة','British','بريطاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'US', 'United States','الولايات المتحدة','American','أمريكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'UM', 'US Minor Outlying Islands','قائمة الولايات والمناطق الأمريكية','US Minor Outlying Islander','أمريكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'UY', 'Uruguay','أورغواي','Uruguayan','أورغواي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'UZ', 'Uzbekistan','أوزباكستان','Uzbek','أوزباكستاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'VU', 'Vanuatu','فانواتو','Vanuatuan','فانواتي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'VE', 'Venezuela','فنزويلا','Venezuelan','فنزويلي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'VN', 'Vietnam','فيتنام','Vietnamese','فيتنامي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'VI', 'Virgin Islands (U.S.)','الجزر العذراء الأمريكي','American Virgin Islander','أمريكي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'VA', 'Vatican City','فنزويلا','Vatican','فاتيكاني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'WF', 'Wallis and Futuna Islands','والس وفوتونا','Wallisian/Futunan','فوتوني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'EH', 'Western Sahara','الصحراء الغربية','Sahrawian','صحراوي',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'YE', 'Yemen','اليمن','Yemeni','يمني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ZM', 'Zambia','زامبيا','Zambian','زامبياني',NULL,NULL);
INSERT INTO `countries` VALUES (NULL,'ZW', 'Zimbabwe','زمبابوي','Zimbabwean','زمبابوي',NULL,NULL);